# Generated by Django 4.2.17 on 2025-04-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0028_alter_userpoint_discord_avatar_link_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banrecord',
            name='is_purged',
        ),
        migrations.RemoveField(
            model_name='banrecord',
            name='purge_window_days',
        ),
    ]
